/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product, FAQItem, ReviewItem } from './types';
import haven006 from './assets/images/haven006.png';
import haven005 from './assets/images/haven005.png';
import haven003 from './assets/images/haven003.png';
import haven007 from './assets/images/haven007.png';

export const products: Product[] = [
  {
    id: 'size-5l',
    name: 'Haven Grace Multipurpose',
    size: '5 Litres',
    priceTsh: 12000,
    priceUsd: 4.60,
    descriptionEng: 'High capacity designed for families and commercial spaces. Maximum cleaning power with deep lemon fresh scent that lasts for weeks.',
    descriptionSwa: 'Kipimo kikubwa kilichoundwa kwa ajili ya familia na biashara. Uwezo mkubwa wa usafi wenye harufu nzuri ya limau inayodumu kwa wiki kadhaa.',
    image: haven006,
    tagEng: 'Premium Value',
    tagSwa: 'Ofa Kabambe',
    tagType: 'primary',
  },
  {
    id: 'size-1l',
    name: 'Haven Grace Multipurpose',
    size: '1 Litre',
    priceTsh: 3500,
    priceUsd: 1.35,
    descriptionEng: 'Perfect for everyday household use. Compact, easy to handle, and consistently powerful on laundry, dishes, and delicate surfaces.',
    descriptionSwa: 'Inafaa kwa matumizi ya kila siku ya nyumbani. Rahisi kubeba, na yenye nguvu kwenye nguo, vyombo, na sakafu zote.',
    image: haven005,
    tagEng: 'Everyday Choice',
    tagSwa: 'Chaguo la Kila Siku',
    tagType: 'tertiary',
  },
  {
    id: 'toilet-cleaner',
    name: 'Haven Grace Toilet Cleaner',
    size: '5 Litres',
    priceTsh: 11000,
    priceUsd: 4.20,
    descriptionEng: 'Specially formulated to eliminate 99.9% of bacteria and dissolve tough limescale. Prevents deep stains and leaves toilets completely sanitised.',
    descriptionSwa: 'Imeundwa maalum kuua 99.9% ya bakteria na kuyeyusha chokaa ngumu nene ya chooni. Huzuia madoa sugu na kuacha choo kikiwa safi mno.',
    image: haven003,
    tagEng: 'Stain Remover',
    tagSwa: 'Ondoa Madoa Sugu',
    tagType: 'primary',
  },
  {
    id: 'handwash',
    name: 'Haven Grace Fresh Handwash',
    size: '500ml Pump',
    priceTsh: 3000,
    priceUsd: 1.15,
    descriptionEng: 'Gentle hand wash featuring organic lemon extract. Deeply hydrates and leaves your hands feeling clean, soft, and refreshed.',
    descriptionSwa: 'Sabuni ya kunawia mikono na dondoo za limau asilia. Inalainisha sana na huacha mikono yako ikiwa safi, yenye harufu nzuri na nyororo.',
    image: haven007,
    tagEng: 'Skin Friendly',
    tagSwa: 'Salama kwa Ngozi',
    tagType: 'tertiary',
  }
];

export const faqs: FAQItem[] = [
  {
    questionEng: 'Can I use Haven Grace for laundry and washing machines?',
    questionSwa: 'Je, naweza kutumia Haven Grace kufua na kwenye mashine ya kufulia?',
    answerEng: 'Absolutely! Haven Grace is meticulously formulated to be low-foam and fabric-gentle, making it perfectly safe for both manual washing and high-efficiency automatic washing machines.',
    answerSwa: 'Kabisa! Haven Grace imeundwa kwa fomula ya povu la wastani inayolinda vitambaa, hivyo ni salama kabisa kwa kufulia kwa mikono na hata mashine za kufulia za kisasa.'
  },
  {
    questionEng: 'Is this detergent safe for sensitive skin or baby clothes?',
    questionSwa: 'Je, sabuni hii ni salama kwa ngozi nyeti au nguo za watoto?',
    answerEng: 'Yes, our detergent is made with balanced pH and gentle skin-safe agents. It thoroughly removes stains while leaving baby clothes soft, clean, and free of harsh chemicals.',
    answerSwa: 'Ndiyo, sabuni yetu imetengenezwa kwa pH iliyosawazishwa na haina kemikali kali. Husafisha madoa yote huku ikiacha nguo za mtoto zikiwa laini, safi na salama kabisa.'
  },
  {
    questionEng: 'Where do you deliver and how long does it take?',
    questionSwa: 'Mnasafirisha wapi na inachukua muda gani kufika?',
    answerEng: 'We deliver countrywide in Tanzania! Dar es Salaam deliveries are typically completed within 2 to 4 hours of ordering, while other major cities receive deliveries within 24 hours.',
    answerSwa: 'Tunasafirisha nchi nzima nchini Tanzania! Usafirishaji wa Dar es Salaam unachukua saa 2 hadi 4 pekee tangu kukamilisha agizo, na mikoa mingine hupokea ndani ya saa 24.'
  },
  {
    questionEng: 'Do you offer wholesale prices for retail shops or bulk buyers?',
    questionSwa: 'Je, mna bei ya jumla kwa maduka au wanunuzi wa kiwango kikubwa?',
    answerEng: 'Yes, we offer special wholesale rates for distributors, hotels, laundromats, and retailers. Contact us via our order form or WhatsApp to get a custom wholesale catalog.',
    answerSwa: 'Ndiyo, tuna bei maalum za jumla kwa wasambazaji, mahoteli, dobi na maduka ya rejareja. Wasiliana nasi kupitia agizo au WhatsApp ili upate katalogi ya bei za jumla.'
  }
];

export const reviews: ReviewItem[] = [
  {
    id: 'rev-1',
    author: 'Grace Neema',
    location: 'Dar es Salaam, Masaki',
    textEng: 'This liquid soap is incredible. Cleaned my greasy kitchen countertops effortlessly and left a beautiful, refreshing scent!',
    textSwa: 'Sabuni hii ya maji ni kiboko! Imesafisha mafuta yote ya jikoni bila nguvu kubwa madoa yote yameisha, na harufu yake ya limau ni tamu sana!',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80'
  },
  {
    id: 'rev-2',
    author: 'Juma Omari',
    location: 'Dar es Salaam, Kinondoni',
    textEng: 'Used the 5L bottle for my young family laundry. It lasts so long, and it is very gentle on hands compared to powders.',
    textSwa: 'Nilitumia dumu la lita tano kwa kufulia nguo za familia yangu. Inadumu sana, na ni laini mikononi tofauti kabisa na unga wa kufulia.',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80'
  }
];

export const dictionary = {
  en: {
    navBenefits: 'Benefits',
    navHowToUse: 'How to Order',
    navOrder: 'Order Now',
    taglineLight: 'Safisha Kibabe.',
    taglineBold: 'Clean with confidence.',
    heroSubtitle: 'The ultimate cleaning companion for your home. Powerful on stains, gentle on hands. Experience a new standard of domestic brilliance.',
    orderNow: 'Order Now',
    learnMore: 'Learn More',
    benefitsTitle: 'Why Choose Haven Grace?',
    benefitsSubtitle: 'Specially engineered formula delivering spotless cleanliness and refreshing aroma.',
    featureCard1Title: 'Deep Clean',
    featureCard1Text: 'Removes tough grease, dirt, and stubborn stains effortlessly, leaving surfaces sparkling like new.',
    featureCard2Title: 'Multi-Surface',
    featureCard2Text: 'One solution for everything. Perfect for washing dishes, ceramic tiling, and your everyday garments.',
    featureCard3Title: 'Lemon Fresh',
    featureCard3Text: 'Infused with long-lasting premium essential oils to leave a deep refreshing citrus scent everywhere.',
    sizesTitle: 'Select Your Perfect Size',
    sizesSubtitle: 'Choose the volume that fits your cleaning routine and budget.',
    highCapacity: 'High capacity for large households.',
    compactSize: 'Ideal for small apartments or daily tests.',
    addToCart: 'Add to Cart',
    howToOrderTitle: 'How to Order',
    howToOrderSub: 'Getting your hands on the freshest clean is simple. Follow our straightforward flow:',
    step1Title: 'Choose Your Size',
    step1Text: 'Select between our multipurpose, toilet cleaner, or hand wash products based on your cleaning needs.',
    step2Title: 'Provide Location',
    step2Text: 'Provide your delivery address and contact information so our dispatch team can locate you promptly.',
    step3Title: 'Instant Delivery',
    step3Text: 'Sit back and relax. Our courier will bring your Haven Grace products straight to your doorstep and you pay on delivery.',
    whatsappOrder: 'Buy via WhatsApp',
    reviewHeading: 'What Our Customers Say',
    reviewSub: 'Real reviews from households who elevated their home clean.',
    contactUs: 'Contact Us',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    allRights: '© 2026 Haven Grace. Safisha Kibabe. All Rights Reserved.',
    shoppingCart: 'Shopping Cart',
    cartEmpty: 'Your cart is empty.',
    subtotal: 'Subtotal',
    checkout: 'Proceed to Checkout',
    checkoutTitle: 'Complete Your Order',
    checkoutSub: 'We support Cash on Delivery (Tigo Pesa / M-Pesa / Airtel Money / Halopesa / Cash).',
    placeholderName: 'Your Full Name',
    placeholderPhone: 'Active Phone Number',
    placeholderLoc: 'Delivery Location (e.g., Masaki, Dar es Salaam)',
    preferredTime: 'Preferred Delivery Time',
    timeOption1: 'Immediate Delivery (Within 3 Hours)',
    timeOption2: 'Evening (4:00 PM - 7:00 PM)',
    timeOption3: 'Tomorrow Morning',
    specialInstructions: 'Special Instructions / Landmarking details',
    orderConfirmation: 'Order Sent Successfully!',
    orderSuccessMessage: 'Thank you for choosing Haven Grace. Your order has been registered. Our dispatch rider will contact you shortly to confirm.',
    trackStatus: 'Delivery Status: In Progress',
    dispatchIn: 'Out for dispatch in: 45 minutes',
    whatsAppConfirm: 'Send Order Details to WhatsApp',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Everything you need to know about Haven Grace detergent.',
    customBundle: 'Order Form / Custom Wholesale'
  },
  sw: {
    navBenefits: 'Faida',
    navHowToUse: 'Jinsi ya Kuagiza',
    navOrder: 'Agiza Sasa',
    taglineLight: 'Safisha Kibabe.',
    taglineBold: 'Safisha kwa uhakika.',
    heroSubtitle: 'Msaidizi bora zaidi wa usafi nyumbani kwako. Nguvu dhidi ya madoa, laini mikononi kwako. Pata usafi wa kiwango cha juu sasa.',
    orderNow: 'Agiza Sasa',
    learnMore: 'Soma Zaidi',
    benefitsTitle: 'Kwa Nini Ushinde na Haven Grace?',
    benefitsSubtitle: 'Fomula iliyotengenezwa kitaalamu kutoa usafi usio na doa na harufu ya kuvutia ya matunda.',
    featureCard1Title: 'Usafi wa Ndani',
    featureCard1Text: 'Huondoa mafuta, uchafu na madoa sugu bila shida, huku ikiacha nyuso zikimeta kama mpya.',
    featureCard2Title: 'Matumizi Mengi',
    featureCard2Text: 'Suluhisho moja kwa kila kitu. Inafaa kwa vyombo, vigae vya ceramic, na kufua nguo zako za kila siku.',
    featureCard3Title: 'Harufu ya Limau',
    featureCard3Text: 'Imetiwa mafuta asilia ya limau ili kuacha harufu ya kitropiki ya kudumu kila unaposafisha.',
    sizesTitle: 'Chagua Kipimo Chako Bora',
    sizesSubtitle: 'Chagua kiwango kinachofaa zaidi matumizi yako ya kila siku na bajeti yako mahususi.',
    highCapacity: 'Kipimo kikubwa cha kudumu kwa familia nzima.',
    compactSize: 'Chaguo mahiri kwa matumizi ya haraka au ya kwanza.',
    addToCart: 'Weka Kwenye Kikapu',
    howToOrderTitle: 'Jinsi ya Kuagiza',
    howToOrderSub: 'Kupata sabuni yako makini yenye usafi wa dhati ni jambo rahisi sana. Fuata njia hii fupi:',
    step1Title: 'Chagua Kipimo',
    step1Text: 'Chagua kati ya bidhaa zetu za sabuni ya multipurpose, sabuni ya chooni, au kunawa mikono.',
    step2Title: 'Weka Mahali Ulipo',
    step2Text: 'Andika anwani ya utoaji na nambari yako ya simu ili wasafirishaji wetu wakufikie kwa urahisi zaidi.',
    step3Title: 'Tusafirishe Papo Hapo',
    step3Text: 'Tulia na upumzike. Msafirishaji wetu ataleta bidhaa za Haven Grace mlangoni pako kisha unalipa ukipokea.',
    whatsappOrder: 'Nunua Kupitia WhatsApp',
    reviewHeading: 'Maoni ya Wateja Wetu',
    reviewSub: 'Shuhuda halisi kutoka kwa familia zilizoboresha kiwango cha usafi nyumbani.',
    contactUs: 'Wasiliana Nasi',
    privacy: 'Sera ya Faragha',
    terms: 'Vigezo na Masharti',
    allRights: '© 2026 Haven Grace. Safisha Kibabe. Haki zote zimehifadhiwa.',
    shoppingCart: 'Kikapu cha Manunuzi',
    cartEmpty: 'Kikapu chako hakina kitu kwa sasa.',
    subtotal: 'Jumla Ndogo',
    checkout: 'Endelea Kulipia',
    checkoutTitle: 'Kamilisha Agizo Lako',
    checkoutSub: 'Tunakubali Malipo Unapopokea (Tigo Pesa / M-Pesa / Airtel Money / Halopesa / Cash).',
    placeholderName: 'Jina Lako Kamili',
    placeholderPhone: 'Namba ya Simu Inayotumika',
    placeholderLoc: 'Eneo la Safirishaji (mfano, Masaki, Dar es Salaam)',
    preferredTime: 'Muda Unaopendelea Kupokea',
    timeOption1: 'Sasa Hivi (Ndani ya Saa 3)',
    timeOption2: 'Jioni (Saa 10 Jioni - Saa 1 Jioni)',
    timeOption3: 'Kesho Asubuhi',
    specialInstructions: 'Maelekezo Maalum au Alama za Barabarani karibu nawe',
    orderConfirmation: 'Agizo Lilitumwa kwa Mafanikio!',
    orderSuccessMessage: 'Asante kwa kuchagua Haven Grace. Agizo lako limesajiliwa kikamilifu. Dereva wetu atawasiliana nawe hivi punde kuthibitisha.',
    trackStatus: 'Hali ya Usafirishaji: Inashughulikiwa',
    dispatchIn: 'Muda wa kutoka kwa msafirishaji: dakika 45',
    whatsAppConfirm: 'Tuma Maelezo ya Agizo kwenye WhatsApp',
    faqTitle: 'Maswali Yanayoulizwa Sana',
    faqSubtitle: 'Kila kitu unachohitaji kufahamu kuhusu sabuni makinika ya Haven Grace.',
    customBundle: 'Fomu ya Agizo / Ununuzi wa Jumla'
  }
};
